server.port: 7002

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db

logging:
  level:
    root: INFO
    by.ilya: DEBUG
---
spring.profiles: docker

spring.data.mongodb.host: mongodb

server.port: 8080

