server.port: 7001

logging:
  level:
    root: INFO
    by.ilya.microservices: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring.profiles: docker

server.port: 8080