server.port: 7003

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd

logging:
  level:
    root: INFO
    by.ilya: DEBUG
---
spring.profiles: docker

spring:
  datasource:
    url: jdbc:mysql://localhost/review-db

server.port: 8080